name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          # Login dockerhub
          pwd="${{ secrets.dockerhub }}"
          docker login -u="plazzari" -p="${pwd}"

          # Build docker images
          docker build . --tag plazzari/cloudtrail-event-fuzzy-viewer:0.1.0
          docker tag plazzari/cloudtrail-event-fuzzy-viewer:0.1.0 plazzari/cloudtrail-event-fuzzy-viewer:latest

          # Deploy docker images
          docker push plazzari/cloudtrail-event-fuzzy-viewer:0.1.0
          docker push plazzari/cloudtrail-event-fuzzy-viewer:latest

          

