name: CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: |
          # Login dockerhub
          pwd="${{ secrets.dockerhub }}"
          docker login -u="plazzari" -p="${pwd}"

          # Get version
          VERSION=$(awk -F '[="]' '/^VERSION/ {print $3}' cloudtrail-event-fuzzy-viewer)

          # Build docker images
          docker build . --tag "plazzari/cloudtrail-event-fuzzy-viewer:${VERSION}"
          docker tag "plazzari/cloudtrail-event-fuzzy-viewer:${VERSION}" plazzari/cloudtrail-event-fuzzy-viewer:latest

          # Deploy docker images
          docker push "plazzari/cloudtrail-event-fuzzy-viewer:${VERSION}"
          docker push plazzari/cloudtrail-event-fuzzy-viewer:latest



